### ISSUE TITLE
Unzip problem

### ISSUE THREAD

**Issue by Murari007** [fardinkhanz/Design-a-2-bit-ALU-with-a-Status-Register-#5]
The Proteus file provided in the repo cannot be unziped.

**Comment by fardinkhanz** [comment]
Thank you for the input. 
The file is working fine, make sure to open it in the directory were proteus 8 is saved, and respective extensions are available in the proteus.
![Screenshot 2024-01-23 111721](https://github.com/fardinkhanz/Design-a-2-bit-ALU-with-a-Status-Register-/assets/89691395/46c3db5f-cc2f-41f6-91f6-dff85f1dc6e1)
![Screenshot 2024-01-23 111732](https://github.com/fardinkhanz/Design-a-2-bit-ALU-with-a-Status-Register-/assets/89691395/c2f1593e-76f7-438d-9e33-8ea44da1d771)
